export const DEFAULT_LEADS_DATA = [
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
  {
    name: "Product 1",
    company: "Company A",
    state: "Calefornia",
    phone: "155 5455 444",
    email: "john@example.com",
    lead_status: "Active",
    action: "Action",
  },
];

export const DEFAULT_FILES = [
  {
    sr_no: "1",
    files_added: "File 1",
  },
];
//CONTACT ADD NEW Notes DTAT
export const NOTES_DATA = [
  {
    id: 1,
    name: "Lori Brayson",
    company: "3M Library Systems",
    bodyText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 2,
    name: "Lori Brayson",
    company: "3M Library Systems",
    bodyText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 3,
    name: "Lori Brayson",
    company: "3M Library Systems",
    bodyText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: 4,
    name: "Lori Brayson",
    company: "3M Library Systems",
    bodyText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
];
//CONTACT ADD NEW EMAIL DATA ARRAY
export const EMAIL_DTAT_LIST = [
  {
    label: "P0",
    name: "John Doe",
    filterEmailText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    month: "Jul",
  },
  {
    label: "P1",
    name: "John Doe",
    filterEmailText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    month: "Aug",
  },
  {
    label: "P2",
    name: "Jane Doe",
    filterEmailText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
    month: "Sep",
  },
  {
    label: "P3",
    name: "Jane Doe",
    filterEmailText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
    month: "Oct",
  },
  {
    label: "P4",
    name: "Jane Doe",
    filterEmailText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
    month: "Nov",
  },
  {
    label: "P5",
    name: "Jane Doe",
    filterEmailText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
    month: "Dec",
  },
  {
    label: "P6",
    name: "Jane Doe",
    filterEmailText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
    month: "Jan",
  },
];
export const MESSAGEDATA = [
  {
    label: "P0",
    number: "(+1) 325-456-7789",
    description:
      "  Hi, I’ve been thinking about using Cuboid software for a while now. I just have few questions in my mind to evaluate if its the right fit for us. Can we schedule a meeting?",
    date: "06/05/2023  11:52 ",
  },
  {
    label: "P0",
    number: "(+1) 325-456-7789",
    description:
      "  Hi, I’ve been thinking about using Cuboid software for a while now. I just have few questions in my mind to evaluate if its the right fit for us. Can we schedule a meeting?",
    date: "06/05/2023  11:52 ",
  },
];
export const LEADS_ACTIVITY_DATA = [
  {
    sr_no: "1",
    activity: "Attachment Created",
    performed_by: "Gaboudian",
    date: "08-31-2023",
    activity_description: "Attachment has been created",
  },
  {
    sr_no: "2",
    activity: "Attachment Created",
    performed_by: "Gaboudian",
    date: "08-31-2023",
    activity_description: "Attachment has been created",
  },
  {
    sr_no: "3",
    activity: "Attachment Created",
    performed_by: "Gaboudian",
    date: "08-31-2023",
    activity_description: "Attachment has been created",
  },
];

export const OPPORTUNITIES_GRID_DATA = [
  {
    sr_no: 1,
    opportunity_name: "Sample Opportunity 1",
    opportunity_owner: "John Doe",
    admin_fee: 5000,
    estimated_close_date: "2023-09-30",
    created_date: "2023-09-15",
    probability: 0.75,
    lead_source: "Web Form",
    annual_payroll: 1000000,
    follow_up: "Yes",
    action: "View Details",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  {
    sr_no: 2,
    opportunity_name: "Sample Opportunity 2",
    opportunity_owner: "Jane Smith",
    admin_fee: 7500,
    estimated_close_date: "2023-10-15",
    created_date: "2023-09-20",
    probability: 0.6,
    lead_source: "Referral",
    annual_payroll: 800000,
    follow_up: "No",
    action: "Edit Opportunity",
  },
  // Add more dummy objects as needed
];

export const CASES_LIST_GRID_DATA = [
  {
    sr_no: 1,
    case_no: "CASE001",
    contact_no: "123-456-7890",
    subject: "Dummy Subject 1",
    priority: "High",
    status: "Open",
    owner: "John Doe",
    assignee: "Jane Smith",
    action: "Do something",
  },
  {
    sr_no: 2,
    case_no: "CASE002",
    contact_no: "987-654-3210",
    subject: "Dummy Subject 2",
    priority: "Medium",
    status: "In Progress",
    owner: "Alice Johnson",
    assignee: "Bob Brown",
    action: "Take action",
  },
  {
    sr_no: 2,
    case_no: "CASE002",
    contact_no: "987-654-3210",
    subject: "Dummy Subject 2",
    priority: "Medium",
    status: "In Progress",
    owner: "Alice Johnson",
    assignee: "Bob Brown",
    action: "Take action",
  },
  {
    sr_no: 2,
    case_no: "CASE002",
    contact_no: "987-654-3210",
    subject: "Dummy Subject 2",
    priority: "Medium",
    status: "In Progress",
    owner: "Alice Johnson",
    assignee: "Bob Brown",
    action: "Take action",
  },
  {
    sr_no: 2,
    case_no: "CASE002",
    contact_no: "987-654-3210",
    subject: "Dummy Subject 2",
    priority: "Medium",
    status: "In Progress",
    owner: "Alice Johnson",
    assignee: "Bob Brown",
    action: "Take action",
  },
  // Add more dummy objects as needed
];

export const CALL_DETAILS_GRID_DATA = [
  {
    sr_no: 1,
    subject: "Lorem Ipsum",
    contact_no: "123-456-7890",
    name: "John Doe",
    account: "Account A",
    comments: "Lorem ipsum dolor sit amet...",
    created_by: "Alice",
    assignee: "Bob",
    action: "Edit",
  },
  {
    sr_no: 2,
    subject: "Dolor Sit Amet",
    contact_no: "987-654-3210",
    name: "Jane Smith",
    account: "Account B",
    comments: "Consectetur adipiscing elit...",
    created_by: "Eve",
    assignee: "Charlie",
    action: "Delete",
  },
  {
    sr_no: 2,
    subject: "Dolor Sit Amet",
    contact_no: "987-654-3210",
    name: "Jane Smith",
    account: "Account B",
    comments: "Consectetur adipiscing elit...",
    created_by: "Eve",
    assignee: "Charlie",
    action: "Delete",
  },
  {
    sr_no: 2,
    subject: "Dolor Sit Amet",
    contact_no: "987-654-3210",
    name: "Jane Smith",
    account: "Account B",
    comments: "Consectetur adipiscing elit...",
    created_by: "Eve",
    assignee: "Charlie",
    action: "Delete",
  },
  {
    sr_no: 2,
    subject: "Dolor Sit Amet",
    contact_no: "987-654-3210",
    name: "Jane Smith",
    account: "Account B",
    comments: "Consectetur adipiscing elit...",
    created_by: "Eve",
    assignee: "Charlie",
    action: "Delete",
  },
  // Add more dummy data objects as needed
];
